version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo Build started on `date`
      # Build the project
      - mvn install
      # create and upload a deployment package
      - aws cloudformation package --template-file sam-template.yaml --s3-bucket cw-lms --output-template-file sam-template-output.yaml
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - sam-template-output.yaml
    - config-*.json